# Generated by Django 4.2.21 on 2025-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friendgroup_grouptodo_groupmeetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeetup',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
