# Generated by Django 5.2.1 on 2025-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_usertimetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertimetable',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='usertimetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usertimetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertimetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
