# Generated by Django 5.2.1 on 2025-07-26 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_usertimetable_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'semester', 'module_code'],
                'unique_together': {('user', 'module_code', 'semester')},
            },
        ),
    ]
